name: mostlyrx
description: A new Flutter project.

publish_to: 'none'

version: 2.0.9+28

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dots_indicator: ^2.1.0
  firebase_auth: ^4.3.0
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.4.1+1
  
  flutter_local_notifications: ^13.0.0
  flutter_polyline_points: ^1.0.0
  flutter_signature_pad: ^3.0.1
  fluttertoast: ^8.0.9
  google_fonts: ^4.0.0
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.18.0
  location: ^4.4.0
  logger: ^1.1.0
  maps_toolkit: ^2.0.1
  onesignal_flutter: ^3.5.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  retry: ^3.1.0
  shared_preferences: ^2.0.15
  soundpool: ^2.3.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  firebase_messaging: ^14.3.0
  # syncfusion_flutter_charts: ^24.1.47+2
  collection: 
  cached_network_image: ^3.2.3
  flutter_svg: 
  timeago: ^3.4.0
  store_version_checker: ^0.0.3
  open_store: ^0.5.0
  assets_audio_player: 

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/raw/
    - assets/vectors/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
